version: '3.3'
services:
  db:
    build:
      context: ./database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/:/data/
      - db_data:/var/lib/mysql

  web:
    build:
      context: ./webapp
    depends_on: 
      - db
    links:
      - db:mysql
    volumes:
      - ./webapp:/var/www/html
    ports:
      - "7000:80"

  api:
    build:
      context: ./api
    depends_on: 
      - db
    links:
      - db:mysql
    volumes:
      - ./api:/var/www/api/
    ports:
      - "7001:3000"
    command: nodemon start app.local.js

#  docs:
#    build:
#      context: ./docs
#    depends_on: 
#      - db
#    links:
#      - db:mysql
#    volumes:
#      - ./docs:/var/www/docs/html
#    ports:
#      - "7002:80"

volumes:
    db_data:
